fix: don't call `file.check_content()` twice
This first call was sometimes done when `_content` wasn't set, resulting in:

```
  File "apps/frappe/frappe/core/doctype/file/file.py", line 138, in validate
    self.check_content()
  File "apps/frappe/frappe/core/doctype/file/file.py", line 381, in check_content
    if self.file_type == "PDF" and self._content and pdf_contains_js(self._content):
                                   ^^^^^^^^^^^^^
AttributeError: 'File' object has no attribute '_content'
```

Just calling it in `write_file()` seems good enough

Signed-off-by: Akhil Narang <me@akhilnarang.dev>
(cherry picked from commit dc2422ebde8019cedb21230d0847d0cb6285777e)